// Generated by CoffeeScript 2.3.0
var os, path;

path = require('path');

os = require('os');

module.exports = function(opts = {}) {
  var CUSH_DIR;
  CUSH_DIR = path.join(os.homedir(), '.cush');
  if (!opts.port) {
    opts.sock || (opts.sock = path.join(CUSH_DIR, 'cdn.sock'));
  }
  opts.log || (opts.log = require('lodge'));
  opts.bucketDir || (opts.bucketDir = path.join(CUSH_DIR, 'buckets'));
  return require('./app')(opts);
};
